import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Provider } from 'urql'
import { client } from '../src/gql/client'

function MyApp({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Provider value={client}>
        <Component {...pageProps} />
      </Provider>
    </>
  )
}

export default MyApp
